import { Platform, StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#EDEDED",
    // paddingTop: Platform.OS === "android" ? 40 : 0,
  },
  header: {
    backgroundColor: "#FBAE3C",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingBottom: 50,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    height: 150,
  },
  backButton: {
    width: 30,
    height: 30,
    backgroundColor: "#F8CF92",
    borderRadius: 8,
    paddingTop: 5,
    paddingLeft: 5,
    marginRight: 10,
  },
  headerTitle: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#000",
  },
  headerIcons: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 10,
  },
  smallAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
  },
  avatarWrapper: {
    alignItems: "center",
    marginTop: -50,
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: "#fff",
  },
  addPhotoBtn: {
    position: "absolute",
    bottom: 0,
    right: "42%",
    backgroundColor: "#FBAE3C",
    borderRadius: 12,
    padding: 4,
  },
  formContainer: {
    paddingHorizontal: 20,
    marginTop: 20,
    paddingVertical: 10,
  },
  label: {
    marginTop: 10,
    marginBottom: 10,
    fontWeight: "500",
    marginLeft: 15,
  },
  input: {
    backgroundColor: "#fff",
    paddingHorizontal: 15,
    paddingVertical: 15,
    marginHorizontal: 15,
    marginBottom: 10,
    borderRadius: 30,
    fontSize: 14,
  },
  updateButton: {
    backgroundColor: "#FBAE3C",
    marginTop: 40,
    marginHorizontal: 15,
    paddingVertical: 12,
    borderRadius: 30,
    alignItems: "center",
    // borderColor: "green",
    // borderWidth: 1,
  },
  updateButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  bottomTab: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 60,
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
  },
  cartIcon: {
    marginRight: 8,
    alignItems: "center",
    backgroundColor: "#F8CF92",
    borderRadius: 8,
    width: 30,
    height: 30,
    paddingTop: 4,
  },
});

export default styles;
