import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E1E2E5",
  },
  header: {
    alignItems: "center",
    paddingTop: 30,
    paddingHorizontal: 20,
    paddingVertical: 20,
    justifyContent: "space-between",
  },
  headerText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    lineHeight: 24,
  },
  topBar: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
  },
  backButton: {
    width: 30,
    height: 30,
    backgroundColor: "white",
    borderRadius: 8,
    paddingTop: 6,
    paddingLeft: 6,
    marginRight: 10,
  },
  cartButton: {
    marginRight: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    borderRadius: 8,
    width: 30,
    height: 30,
  },
  amountOrders: {
    position: "absolute",
    top: -10,
    left: 5,
    backgroundColor: "darkgreen",
    borderRadius: 10,
    height: 15,
    width: 15,
    fontSize: 8,
    color: "#fff",
    textAlign: "center",
    textAlignVertical: "center",
  },
  headerTitle: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#000",
  },
  headerIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  icon: {
    width: 24,
    height: 24,
    marginHorizontal: 10,
  },
  badge: {
    position: "absolute",
    right: 5,
    top: -5,
    // backgroundColor: 'green',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  badgeText: {
    color: "#fff",
    fontSize: 12,
  },
  firstBanner: {
    flexDirection: "row",
    marginHorizontal: 25,
    borderRadius: 18,
    overflow: "hidden",
    alignItems: "center",
    marginTop: 10,
  },
  firstBannerGroup: {
    flex: 1,
    paddingVertical: 15,
    paddingLeft: 35,
    // backgroundColor: 'blue',
  },
  bannerDiscount: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "300",
    marginBottom: 8,
  },
  bannerTitle: {
    color: "#fff",
    fontSize: 30,
    fontWeight: "500",
    lineHeight: 32,
    // backgroundColor: 'red',
  },
  bannerImage: {
    width: 175,
    height: 160,
  },
  secondBanner: {
    position: "relative",
    marginTop: 20,
    marginHorizontal: 25,
  },
  secondBannerGroup: {
    paddingVertical: 20,
    paddingHorizontal: 35,
    alignItems: "flex-start",
  },
  banner2Discount: {
    color: "#fff",
    fontSize: 18,
  },
  banner2Title: {
    color: "#fff",
    fontSize: 45,
    fontWeight: "bold",
  },
  banner2Subtitle: {
    color: "#fff",
    fontSize: 30,
    fontWeight: "500",
  },
  freeDeliveryBadge: {
    position: "absolute",
    // top: -10,
    right: 20,
    height: 45,
    width: 150,
    backgroundColor: "#fff",
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderBottomStartRadius: 20,
    borderBottomEndRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  freeDeliveryText: {
    color: "#FF5733",
    fontSize: 18,
    fontWeight: "bold",
  },
  vouchersTitle: {
    fontSize: 18,
    fontWeight: "bold",
    paddingHorizontal: 25,
    marginTop: 15,
  },
  voucherList: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    padding: 10,
    
    marginHorizontal: 15,
  },
  voucherCard: {
    flexDirection: "column",
    backgroundColor: "#fff",
    width: "48%",
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    alignItems: "center",
  },
  voucherContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    // backgroundColor: 'blue',
  },
  voucherImage: {
    width: 50,
    height: 50,
    borderRadius: 20,
    // backgroundColor: 'blue',
  },
  voucherText: {
    flex: 1,
    // backgroundColor: 'blue',
  },
  voucherTitle: {
    fontSize: 14,
    fontWeight: "bold",
  },
  voucherDiscount: {
    fontSize: 13,
    // color: '#FF6F61',
    color: "#C1C4C7",
    // fontWeight: 'bold',
  },
  voucherLine: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  leftCut: {
    backgroundColor: "#E1E2E5",
    width: 20,
    height: 20,
    borderRadius: 15,
  },
  rightCut: {
    backgroundColor: "#E1E2E5",
    width: 20,
    height: 20,
    borderRadius: 15,
  },
  line: {
    textAlign: "center",
    color: "lightgray",
    fontSize: 20,
  },
  voucherDescription: {
    fontSize: 11,
    color: "#888",
    marginTop: -5,
  },
  voucherTerms: {
    marginTop: 8,
  },
  term: {
    color: "#888",
  },
});

export default styles;
