import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  background: {
    flex: 1,
    width: "100%",
    height: 300,
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 15,
    marginTop: 5,
  },
  headerText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    lineHeight: 24,
  },
  cartIcon: {
    marginRight: 8,
    alignItems: "center",
    backgroundColor: "#F8CF92",
    borderRadius: 8,
    width: 30,
    height: 30,
    paddingTop: 4,
  },
  cartBadge: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "#FF8C42",
    borderRadius: 10,
    width: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
},
cartBadgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "bold",
},
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    marginHorizontal: 20,
    borderRadius: 12,
    paddingHorizontal: 15,
    marginVertical: 10,
    height: 45,
    width: 290,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    height: 40,
    fontSize: 14,
    color: "#333",
  },
  bannerContainer: {
    marginLeft: 20,
    borderRadius: 15,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 30,
    marginVertical: 10,
    position: "relative",
    overflow: "hidden",
    height: 150,
    width: 320,
  },
  textHello: {
    marginRight: 5,
    color: "white",
    fontWeight: "300",
    fontSize: 16,
  },
  textUser: {
    fontWeight: "500",
    color: "white",
    fontSize: 16,
  },
  bannerTextContainer: {
    flex: 1,
    paddingRight: 10,
  },
  bannerText: {
    fontSize: 25,
    fontWeight: "600",
    color: "#fff",
    lineHeight: 25,
  },
  bannerImage: {
    width: 100,
    height: 160,
    marginRight: 10,
  },
  banner2Discount: {
    color: "#fff",
    fontSize: 17,
  },
  banner2Title: {
    color: "#fff",
    fontSize: 42,
    fontWeight: "bold",
  },
  banner2Subtitle: {
    color: "#fff",
    fontSize: 25,
    fontWeight: "bold",
  },
  freeDeliveryBadge: {
    position: "absolute",
    top: -2,
    right: 20,
    height: 45,
    width: 150,
    backgroundColor: "#fff",
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderBottomStartRadius: 20,
    borderBottomEndRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  freeDeliveryText: {
    color: "#FF5733",
    fontSize: 18,
    fontWeight: "bold",
  },
  categoryList: {
    marginVertical: 8,
    width: "100%",
  },
  categoryItem: {
    alignItems: "center",
    marginRight: 10,
    backgroundColor: "#FFF",
    padding: 15,
    borderRadius: 15,
    width: 70,
    height: 80,
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  categoryItemSelected: {
    backgroundColor: "#ff9013",
  },
  categoryText: {
    fontSize: 12,
    color: "#333",
    fontWeight: "500",
    marginTop: 5,
  },
  recommendationHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginTop: 8,
  },
  recommendationTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  // seeAllText: {
  //   fontSize: 12,
  //   color: "#666",
  //   marginRight: 10,
  // },
  productList: {
    paddingHorizontal: 10,
    paddingBottom: 100, // Add padding to ensure content isn't hidden behind tab bar
    marginLeft: 2,
    marginRight: 10,
  },
  productItem: {
    flex: 1,
    backgroundColor: "#fff",
    margin: 8,
    borderRadius: 10,
    paddingTop: 10,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    maxWidth: "46%",
  },
  productImage: {
    width: 80,
    height: 80,
  },
  productName: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
    marginTop: 5,
    textAlign: "center",
  },
  productSource: {
    fontSize: 10,
    color: "#888",
    marginTop: -2,
    marginBottom: 2,
    flexDirection: "row",
    alignItems: "center",
  },
  productPrice: {
    fontSize: 14,
    fontWeight: "bold",
    color: "red",
    marginTop: 2,
  },
  addToCartButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#008374",
    borderTopStartRadius: 15,
    borderTopEndRadius: 15,
    // borderBottomEndRadius: 15,
    // borderBottomStartRadius: 15,
    // width: "100%",
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginTop: 8,
    width: "90%",
    justifyContent: "center",
  },
  addToCartText: {
    color: "#fff",
    fontSize: 12,
    marginLeft: 5,
    fontWeight: "500",
  },
});

export default styles;
